apiVersion: v1
kind: Secret
metadata:
  {{- include "nats.metadataNamespace" $ | nindent 2 }}
  name: {{ .Values.optsSecret.name }}
  labels:
    {{- include "nats.labels" $ | nindent 4 }}
type: Opaque
stringData:
  opts.yaml: |
    {{- toYaml .Values.opts | nindent 4 }}
