{{- include "spl.defaultValues" . }}
{{- with .Values.serviceAccount }}
{{- if .enabled }}
{{- include "spl.loadMergePatch" (merge (dict "file" "service-account.yaml" "ctx" $) .) }}
{{- end }}
{{- end }}
