{{- include "scp.defaultValues" . }}
{{- with .Values.singleReplicaMode }}
{{- if .enabled }}
{{- with .encryptionPvc }}
{{- if .enabled }}
{{- include "scp.loadMergePatch" (merge (dict "file" "pvc.yaml" "ctx" (merge (dict "pvc" .) $)) .) }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
