{{- $config := include "helix.config" . }}
{{- $secretNames := include "helix.secretNames" . }}

{{- $_ := set . "config" (fromJson $config) }}
{{- $_ := set . "secretNames" (fromJson $secretNames) }}
{{- $_ := set . "postgresEnabled" (ternary (get .config "embedded_postgres_enabled") true (hasKey .config "embedded_postgres_enabled")) }}
{{- $_ := set . "prometheusEnabled" (ternary (get .config "embedded_prometheus_enabled") true (hasKey .config "embedded_prometheus_enabled")) }}

---
# deployment.yaml
{{- $deployment := tpl (.Files.Get "files/deployment.yaml") . | fromYaml }}
{{- $deployment = mergeOverwrite $deployment (deepCopy .Values.deploymentTemplate) }}
{{- $deployment = include "jsonpatch" (dict "doc" $deployment "patch" .Values.deploymentPatch) | fromJson }}

{{ toYaml $deployment }}