metadata:
  labels:
    {{- include "scp.labels" $ | nindent 4 }}
  annotations:
    {{- if .Values.podTemplate.configChecksumAnnotation }}
    {{- $configMap := include "scp.loadMergePatch" (merge (dict "file" "config-map.yaml" "ctx" $) $.Values.configMap) }}
    checksum/config: {{ sha256sum $configMap }}
    {{- end }}
spec:
  containers:
  # scp
  {{- $nats := dict }}
  {{- with .Values.container }}
  {{- $nats = include "scp.loadMergePatch" (merge (dict "file" "stateful-set/nats-container.yaml" "ctx" $) .) | fromYaml }}
  - {{ toYaml $nats | nindent 4 }}
  {{- end }}

  # don't need service env vars
  enableServiceLinks: false

  {{- with .Values.serviceAccount }}
  {{- if .enabled }}
  serviceAccountName: {{ .name | quote }}
  {{- end }}
  {{- end }}

  {{- with .Values.podTemplate.topologySpreadConstraints }}
  topologySpreadConstraints:
  {{- range $k, $v := . }}
  - {{ merge (dict "topologyKey" $k "labelSelector" (dict "matchLabels" (include "scp.selectorLabels" $ | fromYaml) "matchLabelKeys" (list "pod-template-hash"))) $v | toYaml | nindent 4 }}
  {{- end }}
  {{- end}}

  volumes:
  - name: config
    configMap:
      name: "{{ include "scp.fullname" . }}-config"
  - name: data
  {{- if and .Values.singleReplicaMode.enabled .Values.singleReplicaMode.dataPvc.enabled (not .config.kms) }}
    persistentVolumeClaim:
      claimName: {{ .dataPvc.name }}
  {{- else }}
    emptyDir: {}
  {{- end}}
  {{- if and .Values.singleReplicaMode.enabled .Values.singleReplicaMode.postgresPvc.enabled (not .config.data_sources.postgres) }}
  - name: postgres
    persistentVolumeClaim:
      claimName: {{ .dataPvc.name }}
  {{- else }}
  {{- if and .Values.singleReplicaMode.enabled .Values.singleReplicaMode.prometheusPvc.enabled (not .config.data_sources.prometheus) }}
  - name: prometheus
    persistentVolumeClaim:
      claimName: {{ .dataPvc.name }}
  {{- else }}
