ports:
{{- range $protocol := list "nats" "leafnode" "websocket" "mqtt" "cluster" "gateway" "monitor" "profiling" }}
{{- $configProtocol := get $.Values.config $protocol }}
{{- $containerPort := get $.Values.container.ports $protocol }}
{{- if or (eq $protocol "nats") $configProtocol.enabled }}
- {{ merge (dict "name" $protocol "containerPort" $configProtocol.port) $containerPort | toYaml | nindent 2 }}
{{- end }}
{{- end }}

{{- with .Values.container.env }}
env:
{{- include "scp.env" . }}
{{- end }}

lifecycle:
  preStop:
    exec:
      # send the lame duck shutdown signal to trigger a graceful shutdown
      command:
      - nats-server
      - -sl=ldm={{ $pidFile }}
volumeMounts:
- name: config
  mountPath: /etc/nats-config
{{- if .Values.reloader.enabled }}
- name: pid
  mountPath: /var/run/nats
{{- end}}
{{- with .Values.config.jetstream }}
{{- if and .enabled .fileStore.enabled .fileStore.pvc.enabled }}
{{- with .fileStore }}
- name: {{ .pvc.name }}
  mountPath: {{ printf "%s/jetstream" .dir | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- with .Values.config.resolver }}
{{- if and .enabled .pvc.enabled }}
- name: {{ .pvc.name }}
  mountPath: {{ .dir | quote }}
{{- end }}
{{- end }}
{{- range $protocol := list "nats" "leafnode" "websocket" "mqtt" "cluster" "gateway" }}
{{- $configProtocol := get $.Values.config $protocol }}
{{- if and (or (eq $protocol "nats") $configProtocol.enabled) $configProtocol.tls.enabled $configProtocol.tls.secretName }}
- name: {{ $protocol }}-tls
  mountPath: {{ $configProtocol.tls.dir | quote }}
{{- end }}
{{- end }}
