name: syn-cp
{{ include "scp.image" (merge (pick .Values "global" "imagePullSecret") .Values.container.image) }}

args:
- server
- start
- -c
- /etc/syn-cp/syn-cp.yaml

{{- with .Values.container.env }}
env:
{{- include "scp.env" . }}
{{- end }}

ports:
- name: http
  containerPort: {{ .Values.config.server.httpPort }}
{{- if .config.server.tls }}
- name: https
  containerPort: {{ .Values.config.server.httpsPort }}
{{- end }}

volumeMounts:
# config secret
- name: config
  mountPath: /etc/syn-cp
{{- $dataDir := trimSuffix "/" .config.data_dir }}
# data emptyDir
- name: data
  mountPath: {{ $dataDir | quote }}
# Single Replica Mode PVCs
{{- with .Values.singleReplicaMode }}
{{- if .enabled }}
{{- with .encryptionPvc }}
{{- if .enabled }}
- name: encryption
  mountPath: {{ printf "%s/encryption" $dataDir | quote}}
{{- end }}
{{- end }}
{{- with .postgresPvc }}
{{- if .enabled }}
- name: postgres
  mountPath: {{ printf "%s/postgres" $dataDir | quote}}
{{- end }}
{{- end }}
{{- with .prometheusPvc }}
{{- if .enabled }}
- name: prometheus
  mountPath: {{ printf "%s/prometheus" $dataDir | quote}}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
# contents secret
{{- if .hasContentsSecret }}
- name: contents
  mountPath: /etc/syn-cp/contents
{{- end }}
# external secrets
{{- range (include "scp.secretNames" $ | fromJson).secretNames }}
- name: {{ .name | quote }}
  mountPath: {{ .dir | quote }}
{{- end }}
