{{- with .Values.config}}

############################################################
# server
############################################################
{{- with .server }}
server:
  {{- include "nats.loadMergePatch" (merge (dict "file" "config/server.yaml" "ctx" $) .) | nindent 2 }}
{{- end }}

############################################################
# systems
############################################################
{{- $hasSystems := false }}
systems:
{{- range $systemName, $system := .systems }}
{{- if .enabled }}
{{- $hasSystems = true }}
  {{ $systemName | quote }}:
    {{- include "nats.loadMergePatch" (merge (dict "file" "config/system.yaml" "ctx" (merge (dict "systemName" $systemName "system" $system) $)) $system) | nindent 4 }}
{{- end }}
{{- end }}
{{- if not $hasSystems -}}
{}
{{- end }}

############################################################
# kms
############################################################
{{- with .kms }}
{{- if .enabled }}
kms:
  {{- include "nats.loadMergePatch" (merge (dict "file" "config/kms.yaml" "ctx" $) .) | nindent 2 }}
{{- end }}
{{- end }}

############################################################
# data sources
############################################################
{{ $hasDataSources := false }}
data_sources:
{{- with .dataSources }}
{{- with .postgres }}
{{- if .enabled }}
{{- $hasDataSources = true }}
  postgres:
    {{- include "nats.loadMergePatch" (merge (dict "file" "config/postgres.yaml" "ctx" $) .) | nindent 4 }}
{{- end }}
{{- end }}
{{- with .prometheus }}
{{- if .enabled }}
{{- $hasDataSources = true }}
  prometheus:
    {{- include "nats.loadMergePatch" (merge (dict "file" "config/prometheus.yaml" "ctx" $) .) | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
{{- if not $hasDataSources -}}
{}
{{- end }}

############################################################
# data dir
############################################################
data_dir: /data

{{- end }}
