{{- with .Values.config.server }}

{{- with .url }}
url: {{ . | quote }}
{{- end }}

http_addr: ":{{ .httpPort }}"
{{- if .tls.enabled }}
https_addr: ":{{ .httpsPort }}"
{{- end }}

{{- with .tls }}
{{- if .enabled }}
tls:
  {{- include "scp.loadMergePatch" (merge (dict "file" "config/tls.yaml" "ctx" (merge (dict "tls" .) $)) .) | nindent 2 }}
{{- end }}
{{- end }}

{{- end }}
