{{- with .tls }}
{{- if .secretName }}
{{- $dir := trimSuffix "/" .dir }}
{{- if and .cert .key }}
cert_file: {{ printf "%s/%s" $dir .cert }}
key_file: {{ printf "%s/%s" $dir .key }}
{{- end }}
{{- if .ca }}
ca_file: {{ printf "%s/%s" $dir .ca }}
{{- end }}
{{- end }}
{{- end }}
