apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.configSecret.name }}
  labels:
    {{- include "scp.labels" $ | nindent 4 }}
type: Opaque
stringData:
  syn-cp.yaml: |
    {{- toYaml .config | nindent 4 }}
