{{- with .Values.imagePullSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    {{- include "scp.labels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {{- $auth := dict "username" .username "password" .password "auth" (printf "%s:%s" .username .password | b64enc) }}
    {{- if .email }}
      {{- $_ := set $auth "email" .email }}
    {{- end }}
    {{- $auths := (dict "auths" (dict .registry $auth)) }}
    {{- toJson $auths | nindent 4 }}
{{- end }}
