{{- with .Values.imagePullSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    {{- include "scp.labels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {{- $auth := dict -}}
    {{- with .username }}
      {{- $_ := set $auth "username" . }}
    {{- end }}
    {{- with .password }}
      {{- $_ := set $auth "password" . }}
    {{- end }}
    {{- if and .username .password }}
      {{- $_ := set $auth "auth" (printf "%s:%s" .username .password | b64enc) }}
    {{- end }}
    {{- $auths := (dict "auths" (dict .registry $auth)) }}
    {{- toJson $auths | nindent 4 }}
{{- end }}
