name: private-link
{{ include "spl.image" (merge (pick .Values "global") .Values.container.image) }}

args:
- --token={{ .Values.config.token }}
- --nats-url={{ .Values.config.natsURL }}
{{- if .Values.config.platformURL }}
- --platform-url={{ .Values.config.platformURL }}
{{- end }}
{{- with .Values.config.tlsClient }}
{{- if and .secretName (and .cert .key) }}
- --tlscert={{ .dir }}/{{ .cert }}
- --tlskey={{ .dir }}/{{ .key }}
{{- end }}
{{- end }}
{{- with .Values.config.tlsCA }}
{{- if and .enabled (or .configMapName .secretName) }}
- --tlsca={{ .dir }}/{{ .key }}
{{- end }}
{{- end }}
{{- if .Values.config.tlsInsecure }}
- --insecure
{{- end }}

{{- with .Values.container.env }}
env:
{{- include "spl.env" . }}
{{- end }}

volumeMounts:
# tlsCA
{{- include "spl.tlsCAVolumeMount" $ }}
# secrets
{{- range (include "spl.secretNames" $ | fromJson).secretNames }}
- name: {{ .name | quote }}
  mountPath: {{ .dir | quote }}
{{- end }}