apiVersion: v1
kind: Secret
metadata:
  {{- include "spl.metadataNamespace" $ | nindent 2 }}
  name: {{ .Values.tokenSecret.name }}
  labels:
    {{- include "spl.labels" $ | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.config.token }}