apiVersion: v2
name: control-plane
description: Synadia Control Plane
home: https://www.synadia.com/
type: application
version: 1.0.2-rc.0
appVersion: 1.1.0-rc.3
maintainers:
- name: Synadia
  url: https://github.com/synadia-io
  email: info@synadia.com
