################################################################################
# Global options
################################################################################
global:
  image:
    # global image pull policy to use for all container images in the chart
    # can be overridden by individual image pullPolicy
    pullPolicy:
    # global registry to use for all container images in the chart
    # can be overridden by individual image registry
    registry:

  # global labels will be applied to all resources deployed by the chart
  labels: {}

################################################################################
# Control Plane Deployment and associated resources
################################################################################

############################################################
# image pull secret
############################################################
imagePullSecret:
  registry: "registry.helix-dev.synadia.io"
  username: ""
  password: ""
  secretTemplate: {}
  secretPatch: []

############################################################
# config
############################################################
# due to the potentially sensitive nature of some of the configuration
# options, the entire configuration will be stored in a Kubernetes Secret
#
config:
  server:
    # URL where Control Plane server will be accessed
    url: ""
    # port for HTTP server to listen on
    httpPort: 8080
    # port for HTTPS server to listen on, TLS must be enabled
    httpsPort: 8433
    # TLS options
    tls:
      enabled: false
      # set secretName in order to mount an existing secret to dir
      secretName:
      dir: /etc/scp-certs/server
      cert: tls.crt
      key: tls.key
      ca:
      # merge or patch the tls config
      merge: {}
      patch: []

    # merge or patch the server config
    merge: {}
    patch: []

  # systems takes a map of System Name : System
  systems:
    Default:
      # enable/disable the system
      enabled: false
      # NATS server URL
      url: ""
      # System User Creds
      systemUserCreds:
        # set contents in order to create a secret with the creds file contents
        contents:
        # set secretName in order to mount an existing secret to to /etc/scp-systems/sys-user-creds/<system-name>
        secretName:
        key: system.creds
      # Operator Signing Key
      operatorSigningKey:
        # set contents in order to create a secret with the nkey file contents
        contents:
        # set secretName in order to mount an existing secret to /etc/scp-systems/operator-sk/<system-name>
        secretName:
        key: operator.nk
      # TLS options
      tls:
        enabled: false
        # set secretName in order to mount an existing secret to dir
        secretName:
        # defaults to /etc/scp-certs/scp-systems/certs/<system-name>
        dir:
        cert: tls.crt
        key: tls.key
        ca:
        # merge or patch the tls config
        merge: {}
        patch: []

      # merge or patch the system config
      merge: {}
      patch: []

  kms:
    # enable/disable explicit KMS configuration
    # when set to false, a default KMS key will be generated and written to the data PVC 
    enabled: false
    key:
      # set to use a KMS URL
      url:value
      # set secretName and key in order to mount an existing secret to to /etc/scp-kms/key
      secretName:
      key: key.enc

    # rotatedKeys is a list of:
    # - # set to use a KMS URL
    #   url:
    #   # set secretName and key in order to mount an existing secret to to /etc/scp-kms/rotated-key-<index>
    #   secretName:
    #   key: key.enc
    rotatedKeys: []

    # merge or patch the KMS config
    merge: {}
    patch: []

  dataSources:
    postgres:
      # enable/disable external PostgreSQL
      enabled: false
      # DSN to external PostgreSQL, TLS settings will be automatically added if supplied
      # DSN will be stored in the config secret since it contains potentially sensitive information
      dsn: ""
      tls:
        enabled: false
        # set secretName in order to mount an existing secret to dir
        secretName:
        dir: /etc/scp-certs/postgres
        cert: tls.crt
        key: tls.key
        ca:
        # merge or patch the tls config
        merge: {}
        patch: []

      # merge or patch the postgres config
      merge: {}
      patch: []

    prometheus:
      # enable/disable external Prometheus
      enabled: false
      # URL to external Prometheus
      url: ""
      tls:
        enabled: false
        # set secretName in order to mount an existing secret to dir
        secretName:
        dir: /etc/scp-certs/postgres
        cert: tls.crt
        key: tls.key
        ca:
        # merge or patch the tls config
        merge: {}
        patch: []

      # merge or patch the prometheus config
      merge: {}
      patch: []

  # merge or patch the config
  merge: {}
  patch: []

############################################################
# deployment
############################################################
deployment:
  # singleReplicaMode must be disabled to set replicas >1
  replicas: 1

  # merge or patch the stateful set
  # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#deployment-v1-apps
  merge: {}
  patch: []
  # defaults to "{{ include "nats.fullname" $ }}"
  name:

############################################################
# deployment -> pod template
############################################################
podTemplate:
  # adds a hash of the Config Secret as a pod annotation
  # this will cause the Deployment to roll when the Config Secret is updated
  configChecksumAnnotation: true

  # map of topologyKey: topologySpreadConstraint
  # labelSelector will be added to match Deployment pods
  #
  # topologySpreadConstraints:
  #   kubernetes.io/hostname:
  #     maxSkew: 1
  #
  topologySpreadConstraints: {}

  # merge or patch the pod template
  # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#pod-v1-core
  merge: {}
  patch: []

############################################################
# deployment -> pod template -> scp container
############################################################
container:
  image:
    repository: registry.helix-dev.synadia.io/helix
    tag: v0.1.0
    pullPolicy: IfNotPresent

  # map with key as env var name, value can be string or map
  # example:
  #
  #   env:
  #     MY_VAR: my_value
  #     MY_SECRET:
  #       valueFrom:
  #         secretKeyRef:
  #           name: secret-name
  #           key: secret-key
  env: {}

  # merge or patch the container
  # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#container-v1-core
  merge: {}
  patch: []

############################################################
# service
############################################################
service:
  enabled: true

  # service port options
  # must be enabled in the config section also
  # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#serviceport-v1-core
  ports:
    http:
      enabled: true
    https:
      enabled: true

  # merge or patch the service
  # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#service-v1-core
  merge: {}
  patch: []
  # defaults to "{{ include "cp.fullname" $ }}"
  name:

############################################################
# ingress
############################################################
# service must be enabled also
ingress:
  enabled: false
  # must contain at least 1 host otherwise ingress will not be created
  hosts: []
  path: /
  pathType: Prefix
  # sets to the ingress class name
  className:
  # set to an existing secret name to enable TLS on the ingress; applies to all hosts
  tlsSecretName:

  # merge or patch the ingress
  # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#ingress-v1-networking-k8s-io
  merge: {}
  patch: []
  # defaults to "{{ include "cp.fullname" $ }}"
  name:

############################################################
# single replica mode
############################################################
singleReplicaMode:
  # in order to disable singleReplicaMode, the following must be configured
  # - config.kms
  # - config.dataSources.postgres
  # - config.dataSources.prometheus
  enabled: true

  ############################################################
  # data pvc
  ############################################################
  # will be mounted if config.kms is not enabled
  dataPvc:
    # enable/disable creation of the PVC
    # WARNING: changing this to false after the PVC is created will result in the PVC being deleted
    enabled: true

    size: 1Gi
    storageClassName:

    # merge or patch the pvc
    # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#persistentvolumeclaim-v1-core
    merge: {}
    patch: []
    # defaults to "{{ include "cp.fullname" $ }}-data"
    name:

  ############################################################
  # postgres pvc
  ############################################################
  # will be mounted if config.dataSources.postgres is not enabled
  postgresPvc:
    # enable/disable creation of the PVC
    # WARNING: changing this to false after the PVC is created will result in the PVC being deleted
    enabled: true

    size: 10Gi
    storageClassName:

    # merge or patch the pvc
    # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#persistentvolumeclaim-v1-core
    merge: {}
    patch: []
    # defaults to "{{ include "cp.fullname" $ }}-postgres"
    name:

  ############################################################
  # prometheus pvc
  ############################################################
  # will be enabled if config.dataSources.prometheus is not enabled
  prometheusPvc:
    # enable/disable creation of the PVC
    # WARNING: changing this to false after the PVC is created will result in the PVC being deleted
    enabled: true

    size: 10Gi
    storageClassName:

    # merge or patch the pvc
    # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#persistentvolumeclaim-v1-core
    merge: {}
    patch: []
    # defaults to "{{ include "cp.fullname" $ }}-prometheus"
    name:

############################################################
# other extension points
############################################################

# config secret
configSecret:
  # merge or patch the config secret
  # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#secret-v1-core
  merge: {}
  patch: []
  # defaults to "{{ include "nats.fullname" $ }}-config"
  name:

# service account
serviceAccount:
  # enable/disable the service account
  enabled: false
  
  # merge or patch the service account
  # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#serviceaccount-v1-core
  merge: {}
  patch: []
  # defaults to "{{ include "nats.fullname" $ }}"
  name:


################################################################################
# Extra user-defined resources
################################################################################
#
# add arbitrary user-generated resources
# example:
#
# extraResources:
# - apiVersion: networking.istio.io/v1beta1
#   kind: VirtualService
#   metadata:
#     name:
#       $tplYaml: >
#         {{ include "nats.fullname" $ | quote }}
#     labels:
#       $tplYaml: |
#         {{ include "nats.labels" $ }}
#   spec:
#     hosts:
#     - demo.nats.io
#     gateways:
#     - my-gateway
#     http:
#     - name: default
#       match:
#       - name: root
#         uri:
#           prefix: /
#       route:
#       - destination:
#           host:
#             $tplYaml: >
#               {{ .Values.service.name | quote }}
#           port:
#             number:
#               $tplYaml: >
#                 {{ .Values.config.server.httpPort }}
#
extraResources: []
