name: control-plane

on:
  pull_request:
    paths:
    - charts/control-plane/**
    - .github/workflows/control-plane.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Setup repo
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        check-latest: true
        cache: true
        cache-dependency-path: charts/control-plane/test/go.sum

    - name: Test
      working-directory: charts/control-plane/test
      run: go test
