name: synadia-server

on:
  pull_request:
    paths:
    - charts/synadia-server/**
    - .github/workflows/synadia-server.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Setup repo
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        check-latest: true
        cache: true
        cache-dependency-path: charts/synadia-server/test/go.sum

    - name: Test
      working-directory: charts/synadia-server/test
      run: go test
