{{- include "scp.defaultValues" . }}
{{- if .hasContentsSecret }}
{{- with .Values.contentsSecret }}
{{- include "scp.loadMergePatch" (merge (dict "file" "contents-secret.yaml" "ctx" $) .) }}
{{- end }}
{{- end }}

