{{- include "scp.defaultValues" . }}
{{- with .Values.imagePullSecret }}
{{- if .enabled }}
{{- include "scp.loadMergePatch" (merge (dict "file" "image-pull-secret.yaml" "ctx" $) .) }}
{{- end }}
{{- end }}
