{{- include "scp.defaultValues" . }}
{{- with .Values.ingress }}
{{- if and .enabled .hosts }}
{{- include "scp.loadMergePatch" (merge (dict "file" "ingress.yaml" "ctx" $) .) }}
{{- end }}
{{- end }}
