{{- $helixSecrets := include "cp.secrets" . | fromJson }}
{{- $helixSecretNames := include "cp.secretNames" . | fromJson }}
{{- $systems := get $helixSecrets "nats_systems" }}

{{- if $helixSecrets }}
{{- range $name, $system := $systems }}
---
# secrets.yaml
{{- if kindIs "map" $system}}
{{- $_ := set $ "name" $name }}
{{- $_ := set $ "system" $system }}
{{- $_ := set $ "secretName" (get $helixSecretNames $name)}}
{{- $secrets := tpl ($.Files.Get "files/secrets.yaml") $ | fromYaml }}
{{- $secrets = mergeOverwrite $secrets (deepCopy $.Values.helix.secretsTemplate) }}
{{- $secrets = include "jsonpatch" (dict "doc" $secrets "patch" $.Values.helix.secretsPatch) | fromJson }}
{{ toYaml $secrets }}
{{- end }}
{{- end }}
{{- end }}

{{- if and .Values.imageCredentials.username .Values.imageCredentials.password }}
---
# pull-secret.yaml
{{- $secrets := tpl (.Files.Get "files/pull-secret.yaml") . | fromYaml }}
{{- $secrets = mergeOverwrite $secrets (deepCopy $.Values.imageCredentials.secretTemplate) }}
{{- $secrets = include "jsonpatch" (dict "doc" $secrets "patch" $.Values.imageCredentials.secretPatch) | fromJson }}
{{ toYaml $secrets }}
{{- end }}
