{{- $config := include "scp.config" . }}

{{- $_ := set . "config" (fromJson $config) }}

---
# serviceaccount.yaml
{{- $serviceAccount := tpl (.Files.Get "files/serviceaccount.yaml") . | fromYaml }}
{{- $serviceAccount = mergeOverwrite $serviceAccount (deepCopy .Values.serviceAccountTemplate) }}
{{- $serviceAccount = include "jsonpatch" (dict "doc" $serviceAccount "patch" .Values.serviceAccountPatch) | fromJson }}
{{ toYaml $serviceAccount }}