apiVersion: v2
name: helix
description: Synadia Helix Chart
home: https://github.com/connecteverything/helix
type: application
version: 0.0.1-alpha
appVersion: "alpha"
maintainers:
- name: Samuel Attwood
  url: https://github.com/samuelattwood
  email: sam@synadia.com